package day2

import (
	"bufio"
	"fmt"
	"strings"
)

var keypad1 = map[rune]map[rune]rune{
	'1': {'R': '2', 'D': '4'},
	'2': {'L': '1', 'R': '3', 'D': '5'},
	'3': {'L': '2', 'D': '6'},
	'4': {'U': '1', 'R': '5', 'D': '7'},
	'5': {'L': '4', 'U': '2', 'R': '6', 'D': '8'},
	'6': {'L': '5', 'U': '3', 'D': '9'},
	'7': {'U': '4', 'R': '8'},
	'8': {'L': '7', 'U': '5', 'R': '9'},
	'9': {'L': '8', 'U': '6'},
}

var keypad2 = map[rune]map[rune]rune{
	'1': {'D': '3'},
	'2': {'R': '3', 'D': '6'},
	'3': {'L': '2', 'U': '1', 'R': '4', 'D': '7'},
	'4': {'L': '3', 'D': '8'},
	'5': {'R': '6'},
	'6': {'L': '5', 'U': '2', 'R': '7', 'D': 'A'},
	'7': {'L': '6', 'U': '3', 'R': '8', 'D': 'B'},
	'8': {'L': '7', 'U': '4', 'R': '9', 'D': 'C'},
	'9': {'L': '8'},
	'A': {'U': '6', 'R': 'B'},
	'B': {'L': 'A', 'U': '7', 'R': 'C', 'D': 'D'},
	'C': {'L': 'B', 'U': '8'},
	'D': {'U': 'B'},
}

var Input = `LLULLLRLDLLLRLUURDDLRDLDURULRLUULUDDUDDLLLURRLDRRLDRRRLDUDLRDLRRDLLDUDUDUDRLUDUUDLLLRDURUDUULUDLRDUUUDUUDURLDUULLRDLULDUURUDRDDLDRLURLRURRDUURLRLUURURUUULLRLLULRUURLULURDLLRRUDLUDULDRDRLRULUURRDRULLRUUUDLRLDLUURRRURDLUDDRRUDRLUDRDLLLLLRULLDUDRLRRDDULDLRUURRRRRLDLDLRDURDRUUURDLRDDDDULURRRRDUURLULLLDLRULRDULRUDLRRLRDLLRLLLUDDLRDRURDDLLLLDUDRDLRURRDLRDDDLDULDRLRULUUDRRRUUULLLURRDDUULURULDURRLLULLDRURUUULRLRDRRUDRDRRDURRUUUULDRDDDUDLDDURLLRR
LDLRRRUURDLDDRLRRDLLULRULLLUDUUDUDLRULLDRUDRULLDULURDRDDLRURDDULLLLDLRDRDRDDURLURLURLUDRDDRDULULUDDRURRDLLDUURDRDDLRLLURRDLRDDULDLULURDRDLUDRRUUDULLULURRDUDRUUUDRULDLDURLRRUDURLDLRRUURRRURDLUDRLDUDRRUDUURURUDDUUDRDULRDLUDRRRLDRURLLRDDDLUDRDUDURDDDRRDDRRRLLRRDDLDDLRUURRURDLLDRLRRDLLUDRRRURURLRDRLLRLRLRULLRURLDLRRULLRRRDULUUULDRDLLURDDLDLRDRLUUDLLUDDLDRRLDLRUDRUDLLUURLLULURUDUDRLULLUDRURDDLDLDDUDLRDDRRURLRLLUDDUDRUURRURRULDRLDDRLLRRLDDURRDLDULLLURULLLRUURLRRRRUUULRLLLURRLRLRUDRDUUUDUUUDDLULLDLLLLDLDRULDRUUULDDDLURLDLRLULRUDDDDURDDLU
RURLURRDLDULLULDDDLRUULLUURLRUDRUDRRUDDLDDDDRRDLRURLRURLDDDUDDUURRDRULDRRRULRDRDDLRUDULRLURDUUDRRLDLRDRURDLDRRRRDRURUUDDDLLRDRDUDUDUDLLULURULRRLRURUULUULDDDDURULRULLRUDUURLURDUDLUDLUDRLLDUUDUULRLRLUUDRDULDULRURDRRRULRUDLRURDDULUDULLRLRURURUULLULDRURLLRRUUDDUUURRDLURUURULRDRRDDUDULRDDLUDLURURUURDRULLRDDLLRDDLDRDUDRRDLUURRLRLUURRULUDURLDDRLLURRDDDLDDRURULLDDRLUDDLRLURDUDULLRDULLLDLLUDDRUDRUDDUUDRDRULRL
RLRDRDULULUDLUDRDRLUDLDLLUDURULDDDUDLRURLLRLRLDLDRLDURDLRRURLULLULURLLDRRDRLUDRLRDLLULRULURRURURUULRDUDLLRDLRRRRRLUURDRRRDLRUDLLDLLDLRUUUDLLLDDDLRDULLRUUDDRLDDURRRDLRLRLDDDDLRDRULLUURUUDRRLLRLLRDDLLRURRRRDRULRRLLRLLLRLDRRLDDDURRURLDURUURRLRLRLDRURULLRLRUDLDUURDLLRLDLURUUUDLLRDRDDDDDDRLDRRRLRRRRURUDLDDRDLLURUDLRRLDDDLUDUDUULRDULULUDDULUUDLLLLRLDDUUULRLRDULURDURRRURRULURRRDRDLDDURDLURUDURRRDDRLRLUDLUDDLUULLDURLURDDUDDLRUUUDRLLDRURL
ULUDLLUDDULRUURDRURDUDUDLUURDDDRRLUDURURDRURRLDRDURLRLLRRDDRRDRRRUULURUDURUDULRRRRDDLDURRLRRDUDDDRLLLULDRLRLURRDUURDURRRURRDLUDUDDRLDLURRRDDRLLRDRDDRDURRRRLURRLUDDURRULRUDUDULDRUDDRULLUUULDURRRLDRULLURULLRUDLDUDDLDULDLUUDRULULDLLDRULLRUULDUDUUDRLRRLDLUULUDLLDDRLRRDDLLURURDULRRDDRURDRLRLULDLDURULLUUUDURURDLDUDDDDUUULUDLUURRULLDLRLURDLURLRLDDURRLDDRRRDUUULLUULDLLDLLDDRLRRUDLULDRLULDULULRRLRULUUURURUUURDUUDDURLLUDDRLRDDLUURRUULRDLDDRLULUULRDRURLUURDRDUURUDLRR`

func Solve() string {
	scanner := bufio.NewScanner(strings.NewReader(Input))
	scanner.Split(bufio.ScanLines)
	digits := []rune{}

	currentDigit := '5'
	for scanner.Scan() {
		instruction := scanner.Text()

		for _, v := range instruction {
			if nextDigit, ok := keypad1[currentDigit][v]; ok {
				currentDigit = nextDigit
			}
		}

		digits = append(digits, currentDigit)
	}
	return string(digits)
}

func SolvePart2() string {
	scanner := bufio.NewScanner(strings.NewReader(Input))
	scanner.Split(bufio.ScanLines)
	keys := []rune{}

	currentKey := '5'
	for scanner.Scan() {
		instruction := scanner.Text()

		for _, v := range instruction {
			nextKey, ok := keypad2[currentKey][v]
			fmt.Printf("%c %c %c\n", currentKey, v, nextKey)
			if ok {
				currentKey = nextKey
			}
		}

		keys = append(keys, currentKey)
	}
	return string(keys)
}
